### ISSUE TITLE
Alternative for the error: UnboundLocalError: local variable 'pH_opt' referenced before assignment

### ISSUE THREAD

**Issue by PabloGGaray** [Electrostatics/pdb2pqr#33] opened 2019-10-18 19:06 UTC
Hi, I was using the [pdb2pqr server](http://nbcr-222.ucsd.edu/pdb2pqr_2.1.1/) to convert my pdb file to pqr file, using PROPKA to assign protonation states at pH 7 (AMBER selected as forcefield and for output naming). But the calculation ended with this error message in the file stderr from the server:

```
Traceback (most recent call last):
  File "/opt/pdb2pqr_2.1.1/pdb2pqr.py", line 62, in <module>
    mainCommand(sys.argv)
  File "main.py", line 740, in mainCommand
  File "main.py", line 339, in runPDB2PQR
  File "src/routines.py", line 1596, in runPROPKA
  File "propka30/Source/protein.py", line 581, in writePKA
  File "propka30/Source/output.py", line 174, in writePKA
  File "propka30/Source/output.py", line 283, in getFoldingProfileSection
  File "propka30/Source/protein.py", line 629, in getPHopt
UnboundLocalError: local variable 'pH_opt' referenced before assignment
```

Then I downloaded apbs-pdb2pqr from this repository and, after the installation, I run pdb2pqr locally, trying to use the minor amount of parameters possible with the following command:

```
python pdb2pqr.py --ff=AMBER --with-ph=7.0 --ph-calc-method=propka --ffout=AMBER GDH454.pdb GDH454_pka.pqr
```

But, this created an empty file "_GDH454_pka.propka_" and return the following error:

```
writing pkafile GDH454_pka.propka
Traceback (most recent call last):
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/pdb2pqr.py", line 62, in <module>
    mainCommand(sys.argv)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/main.py", line 740, in mainCommand
    include_old_header = options.include_header)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/main.py", line 339, in runPDB2PQR
    myRoutines.runPROPKA(ph, ff, outroot, pkaname, ph_calc_options)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/src/routines.py", line 1596, in runPROPKA
    myPkaProtein.writePKA(options=options, filename=outname)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/propka30/Source/protein.py", line 581, in writePKA
    output.writePKA(self, filename=filename, reference=reference, direction=direction, options=options)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/propka30/Source/output.py", line 174, in writePKA
    str += getFoldingProfileSection(protein, reference=reference, direction=direction, window=[0., 14., 1.0], options=options)
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/propka30/Source/output.py", line 283, in getFoldingProfileSection
    pH, dG = protein.getPHopt()
  File "/home/pgaray/Programas/apbs-pdb2pqr/pdb2pqr/propka30/Source/protein.py", line 629, in getPHopt
    self.property["pH-opt"] = [pH_opt, dG_opt]
UnboundLocalError: local variable 'pH_opt' referenced before assignment
```

How you can see is the same error obtained from the server.

Searching in the file "_apbs-pdb2pqr/pdb2pqr/propka30/Source/protein.py_" I found that the variable `pH_opt` wasn't created before line 629 because in the previous `if` the condition `dG < dG_opt` never was achieved (line 627). So, changing the previous assignation in the values of `dG_opt` from `999.` to `999999.` (little exaggeration) the error can be avoided and I got the corresponding pqr file, using the same command that I mentioned before. I suppose that this happens because I have a tetrameric protein and the default value of `dG_opt` isn't big enough to get a result from propka.

I don't know if this is a useful practice and I know this error was mentioned in another Issue Electrostatics/apbs-pdb2pqr#466, but maybe it is useful for avoiding this error in the server,  or if somebody gets the same error when running this repository locally.
Regards.

**Comment by intendo** [comment] 2021-01-11 19:18
@sobolevnrm didn't we drop PROPKA from the pdb2pqr? Is this a propka issue? I don't know how to reproduce this in the new pdb2pqr since we ported it to Python 3. How would we run the equivalent of the command below?

```
python pdb2pqr.py --ff=AMBER --with-ph=7.0 --ph-calc-method=propka --ffout=AMBER GDH454.pdb GDH454_pka.pqr
```

**Comment by sobolevnrm** [comment] 2021-01-12 13:50
> @sobolevnrm didn't we drop PROPKA from the pdb2pqr? Is this a propka issue? I don't know how to reproduce this in the new pdb2pqr since we ported it to Python 3. How would we run the equivalent of the command below?
> 
> ```
> python pdb2pqr.py --ff=AMBER --with-ph=7.0 --ph-calc-method=propka --ffout=AMBER GDH454.pdb GDH454_pka.pqr
> ```
> 
> I think the following would be the new way to run pdb2pqr but I don't have the GDH454.pbd file and can't find it in the Protein Data Bank:
> 
> ```
> python pdb2pqr --ff=AMBER --titration-state-method=propka --ffout=AMBER GDH454.pdb GDH454_pka.pqr
> ```

Nope:  we dropped PDB2PKA but kept PROPKA.

**Comment by intendo** [comment] 2021-01-12 17:17
@sobolevnrm, do you know where I can get GDH454.pdb so we can test this out and close this ticket?

**Comment by sobolevnrm** [comment] 2021-01-12 17:19
> @sobolevnrm, do you know where I can get GDH454.pdb so we can test this out and close this ticket?

@PabloGGaray would need to provide it.

**Comment by intendo** [comment] 2021-01-12 18:31
@sobolevnrm since this originally started with a problem on the UCSD server, I think this problem is no longer relevant. I think @PabloGGaray should be able to use https://server.poissonboltzmann.org/ instead. This issue should probably be closed out.

**Comment by sobolevnrm** [comment] 2021-01-13 02:52
Sounds good; thank you.

**Closed by sobolevnrm** 2021-01-13 02:52 UTC
