### ISSUE TITLE
Final atom numbering in PQR is incorrect

### ISSUE THREAD

**Issue by dvdesolve** [Electrostatics/pdb2pqr#132] opened 2020-11-25 11:37 UTC
Seems like final numbering in PQR file is incorrect. This is what I get after running PDB2PQR (just a first 50 lines):
```
ATOM      1  N   SER     1      27.496  31.222  28.262  0.1849 1.8240
ATOM      2  CA  SER     1      27.785  31.042  26.803  0.0567 1.9080
ATOM      3  C   SER     1      27.906  29.537  26.564  0.6163 1.9080
ATOM      4  O   SER     1      27.364  28.975  25.640 -0.5722 1.6612
ATOM      5  CB  SER     1      29.012  31.766  26.331  0.2596 1.9080
ATOM      6  OG  SER     1      30.194  31.000  26.253 -0.6714 1.7210
ATOM      1  H1  SER     1      26.542  31.486  28.372  0.1898 0.6000
ATOM      1  HA  SER     1      27.004  31.377  26.304  0.0782 1.1000
ATOM      1  HB2 SER     1      28.830  32.161  25.408  0.0273 1.3870
ATOM      1  HB3 SER     1      29.189  32.557  26.951  0.0273 1.3870
ATOM      1  H2  SER     1      27.668  30.363  28.734  0.1898 0.6000
ATOM      1  H3  SER     1      28.090  31.934  28.624  0.1898 0.6000
ATOM      1  HG  SER     1      30.208  30.327  26.993  0.4239 0.0000
ATOM      7  N   SER     2      28.564  28.878  27.515 -0.4157 1.8240
ATOM      8  CA  SER     2      28.674  27.433  27.549 -0.0249 1.9080
ATOM      9  C   SER     2      27.273  26.844  27.733  0.5973 1.9080
ATOM     10  O   SER     2      26.826  25.801  27.202 -0.5679 1.6612
ATOM     11  CB  SER     2      29.652  27.146  28.701  0.2117 1.9080
ATOM     12  OG  SER     2      30.387  28.338  29.025 -0.6546 1.7210
ATOM      7  H   SER     2      28.998  29.502  28.241  0.2719 0.6000
ATOM      7  HA  SER     2      29.021  27.119  26.668  0.0843 1.3870
ATOM      7  HB2 SER     2      29.139  26.863  29.496  0.0352 1.3870
ATOM      7  HB3 SER     2      30.290  26.448  28.414  0.0352 1.3870
ATOM      7  HG  SER     2      30.021  28.725  29.866  0.4275 0.0000
ATOM     13  N   SER     3      26.416  27.561  28.467 -0.4157 1.8240
ATOM     14  CA  SER     3      25.057  27.186  28.762 -0.0249 1.9080
ATOM     15  C   SER     3      24.015  27.530  27.716  0.5973 1.9080
ATOM     16  O   SER     3      22.865  27.149  27.837 -0.5679 1.6612
ATOM     17  CB  SER     3      24.630  27.947  30.050  0.2117 1.9080
ATOM     18  OG  SER     3      25.560  27.616  31.064 -0.6546 1.7210
ATOM     13  H   SER     3      26.848  28.467  28.826  0.2719 0.6000
ATOM     13  HA  SER     3      25.033  26.163  28.896  0.0843 1.3870
ATOM     13  HB2 SER     3      24.667  28.907  29.866  0.0352 1.3870
ATOM     13  HB3 SER     3      23.737  27.639  30.306  0.0352 1.3870
ATOM     13  HG  SER     3      26.135  26.859  30.756  0.4275 0.0000
ATOM     19  N   GLU     4      24.356  28.363  26.737 -0.5163 1.8240
ATOM     20  CA  GLU     4      23.370  28.880  25.827  0.0397 1.9080
ATOM     21  C   GLU     4      23.055  27.958  24.640  0.5366 1.9080
ATOM     22  O   GLU     4      23.937  27.450  23.989 -0.5819 1.6612
ATOM     23  CB  GLU     4      23.907  30.215  25.273  0.0560 1.9080
ATOM     24  CG  GLU     4      22.953  30.893  24.324  0.0136 1.9080
ATOM     25  CD  GLU     4      23.186  32.384  24.168  0.8054 1.9080
ATOM     26  OE1 GLU     4      23.239  33.074  25.208 -0.8188 1.6612
ATOM     27  OE2 GLU     4      23.290  32.799  23.000 -0.8188 1.6612
ATOM     19  H   GLU     4      25.367  28.594  26.697  0.2936 0.6000
ATOM     19  HA  GLU     4      22.499  29.071  26.328  0.1105 1.3870
ATOM     19  HB2 GLU     4      24.053  30.810  26.040 -0.0173 1.4870
ATOM     19  HB3 GLU     4      24.735  30.016  24.787 -0.0173 1.4870
ATOM     19  HG2 GLU     4      23.057  30.484  23.428 -0.0425 1.4870
ATOM     19  HG3 GLU     4      22.031  30.775  24.664 -0.0425 1.4870
```

**Comment by sobolevnrm** [comment] 2020-11-26 02:43
Can you please provide the file that caused this problem?  Thanks.

**Comment by dvdesolve** [comment] 2020-11-26 05:57
`pdb2pqr30 --ff=AMBER --ffout=AMBER --titration-state-method=propka --with-ph=7.5 holoenzyme.pdb holoenzyme_H.pqr`

[holoenzyme.pdb.txt](https://github.com/Electrostatics/pdb2pqr/files/5600761/holoenzyme.pdb.txt) (renamed due to GH limitations)
[holoenzyme_H.pqr.txt](https://github.com/Electrostatics/pdb2pqr/files/5600762/holoenzyme_H.pqr.txt) (renamed due to GH limitations)
[pdb2pqr.log](https://github.com/Electrostatics/pdb2pqr/files/5600763/pdb2pqr.log)

Calcium is added to the `dat/AMBER.DAT` by me:
```
CA	CA	2.000000	1.6490	Ca2+
```

**Comment by sobolevnrm** [comment] 2020-11-27 22:57
FWIW, this problem doesn't happen with the server which means it must be a bug I've introduced since then -- I can reproduce it with the head of the master branch.

**Comment by sobolevnrm** [comment] 2020-11-27 23:53
Actually, it looks like #127 beat you to this.  I fixed it a few days ago in https://github.com/Electrostatics/pdb2pqr/pull/128; the fix is in the master branch now.  Thanks again.

**Closed** 2020-11-29 08:40 UTC
