### ISSUE TITLE
pip fails to install "requests" package

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/pdb2pqr#202] opened 2021-07-06 01:45 UTC
Running from a clean conda environment:

```
pip install pdb2pqr
```

fails to install the `requests` package which becomes apparent when running pdb2pqr.

**Comment by intendo** [comment] 2021-08-05 18:15
@sobolevnrm did this get fixed in version 3.2.0?
I cannot reproduce this error.
I ran `pip uninstall requests` (which was not installed) and then `pip install pdb2pqr` and got the output below showing that `requests` did get installed:

```
Collecting pdb2pqr
  Downloading pdb2pqr-3.2.0-py2.py3-none-any.whl (207 kB)
     |████████████████████████████████| 207 kB 6.0 MB/s 
Requirement already satisfied: mmcif-pdbx>=1.1.2 in /data/home/ubuntu/.local/lib/python3.8/site-packages (from pdb2pqr) (2.0.1)
Requirement already satisfied: numpy in /data/home/ubuntu/.local/lib/python3.8/site-packages (from pdb2pqr) (1.21.1)
Collecting propka>=3.2
  Downloading propka-3.4.0-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 12.1 MB/s 
Requirement already satisfied: requests in /data/home/ubuntu/anaconda3/lib/python3.8/site-packages (from pdb2pqr) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/home/ubuntu/anaconda3/lib/python3.8/site-packages (from requests->pdb2pqr) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /data/home/ubuntu/anaconda3/lib/python3.8/site-packages (from requests->pdb2pqr) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /data/home/ubuntu/anaconda3/lib/python3.8/site-packages (from requests->pdb2pqr) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /data/home/ubuntu/anaconda3/lib/python3.8/site-packages (from requests->pdb2pqr) (4.0.0)
Installing collected packages: propka, pdb2pqr
Successfully installed pdb2pqr-3.2.0 propka-3.4.0
```

**Comment by Eo300** [comment] 2021-08-05 18:26
Looks to be the case.. Found the declaration within the `setup.py`: https://github.com/Electrostatics/pdb2pqr/blob/v3.2.0/setup.py#L59

**Comment by intendo** [comment] 2021-08-05 19:11
I think we can close this now and reopen it if someone finds it is still a problem.

**Closed by intendo** 2021-08-05 19:11 UTC
