### ISSUE TITLE
Broken biomolecule with pdb2pqr30 but works on webserver. 

### ISSUE THREAD

**Issue by marcushock** [Electrostatics/pdb2pqr#192] opened 2021-05-28 15:38 UTC
I'm trying to convert a PDB structure of myosin from an MD simulation into a pqr file.  When using the web server online, I am able to successfully convert it, however using the command line interface, I'm having issues, and get the error that there is a gap in the biomolecule structure. 
In the command line interface I'm using the command:
`pdb2pqr30 --titration-state-method=propka --with-ph=7 --ff=PARSE --whitespace --drop-water myosin.pdb myosin.pqr`

I'm using the same settings on the webserver where it works. Also, this is using pdb2pqr30 version 3.4.0.

I've attached the myosin structure that I'm having issues with. 

[myosin.zip](https://github.com/Electrostatics/pdb2pqr/files/6561849/myosin.zip)

**Comment by sobolevnrm** [comment] 2021-11-21 22:43
We have upgraded the webserver.  Do you have a structure we can use to test if the problem persists after the upgrade?

**Comment by mishaguy** [comment] 2021-11-21 23:13
Hi Nathan,

Thanks for thinking about me.

First of all, it is not on the webserver where this error occurs. It is rather when I use pdb2pqr from PyMol plugin.

I have updated now to your 3.2.2 and no, it is still producing error with default pd2pqr method.

It is now actually producing more complicated error log than 3.2.0.
I have attached it here.

The structure producing error is for instance 4e8m.

Hope this will be resolved soon and thanks for the great tool you provide to research community.

Best,
Misha
[pdb2pqr.log](https://github.com/Electrostatics/pdb2pqr/files/7577347/pdb2pqr.log)

**Comment by sobolevnrm** [comment] 2021-11-24 03:38
Hi Misha --

I don't know much about PyMOL but am wondering if @speleo3 could suggest someone to help.

What version of Python does your PyMOL use?

Thanks

**Comment by sobolevnrm** [comment] 2021-11-25 02:57
This PyMOL issue appears to be a duplicate of #236

**Comment by marcushock** [comment] 2021-11-29 20:31
Sorry about the delay responding, I am still having issues however. I've attached the molecule I'm having issues with in the original post. ([myozin.zip](https://github.com/Electrostatics/pdb2pqr/files/6561849/myosin.zip)) Interestingly, previous versions (such as from PyMol) do not have any issues.

**Comment by speleo3** [comment] 2021-12-18 08:36
I can reproduce this without PyMOL, using the latest PDB2PQR (`v3.4.0`, `cc31e1351bcd`).
```bash
pdb2pqr30 --ff=AMBER myosin.pdb out.pqr
```

> CRITICAL:Unable to debump biomolecule. Biomolecular structure is incomplete:  Found gap in biomolecule structure for atom ATOM  12959  H2  PRO   813     211.335 243.791 177.912  0.0000 0.0000
> CRITICAL:Giving up.

Residues 810-812 are missing. PRO 813 is missing the N-terminal nitrogen, it's capped with HA (hydrogen) instead.

No such error with PDB2PQR 2.1.2

**Comment by speleo3** [comment] 2021-12-18 10:09
There is a `DA` residue with residue number 812 (right before PRO 813), but it's not an amino acid and it's not connected to PRO 813. Changing its chain identifier from `A` to `B` fixes the issue for me.

**Comment by sobolevnrm** [comment] 2021-12-18 15:40
Thank you!

**Comment by mishaguy** [comment] 2021-12-18 23:23
Hi, thanks for this.

One note, I did understand from the beginning that I could fix this issue in structure myself.
However, I can’t advise my users to do this. They are just scientists and not away what is going on in background.

It might be PDB issue. However, as you mentioned it does not occur with previous pdb2pqr.

Best,
Misha

Mikhael Guy
Research Scientist
Science Research Software Core
Yale Center for Research Computing
Yale University
P.O. Box 208107
Sterling Chemistry Laboratory
225 Prospect Street, Rm. 154
New Haven, CT 06520
203.436.8599
For questions related to scientific, analytical and computational software, please e-mail at ***@***.***

**Comment by sobolevnrm** [comment] 2021-12-31 03:21
> Hi Nathan,
> 
> Thanks for thinking about me.
> 
> First of all, it is not on the webserver where this error occurs. It is rather when I use pdb2pqr from PyMol plugin.
> 
> I have updated now to your 3.2.2 and no, it is still producing error with default pd2pqr method.
> 
> It is now actually producing more complicated error log than 3.2.0. I have attached it here.
> 
> The structure producing error is for instance 4e8m.
> 
> Hope this will be resolved soon and thanks for the great tool you provide to research community.
> 
> Best, Misha [pdb2pqr.log](https://github.com/Electrostatics/pdb2pqr/files/7577347/pdb2pqr.log)

The issue with 4E8M was just fixed in https://github.com/Electrostatics/pdb2pqr/commit/6673aabb1d424594785d5d5b36fa3cc69aec4db5.

**Closed by sobolevnrm** 2021-12-31 03:21 UTC

**Comment by mishaguy** [comment] 2021-12-31 14:41
Hi Nathan,

I go to web service and run 4e8m with default parameters.
It still has errors. The log says it is unable to proceed and does not let to go to APBS step.
I see it is running v. 3.4.0.
pip actually gives me now 3.4.1 but I have the same issue.
What version are you using to get all this running properly and where to get it?

Thans,
Misha

Mikhael Guy
Research Scientist
Science Research Software Core
Yale Center for Research Computing
Yale University
P.O. Box 208107
Sterling Chemistry Laboratory
225 Prospect Street, Rm. 154
New Haven, CT 06520
203.436.8599
For questions related to scientific, analytical and computational software, please e-mail at ***@***.***

**Comment by sobolevnrm** [comment] 2021-12-31 14:55
You'll have to pull it from the master branch in Git until I get a new release out (hopefully today).
