### ISSUE TITLE
water hydrogen element error

### ISSUE THREAD

**Issue by dongdawn** [Electrostatics/pdb2pqr#193] opened 2021-05-30 10:03 UTC
![image](https://user-images.githubusercontent.com/29708306/120100020-1902a100-c171-11eb-9d99-3e0b3763db70.png)
After adding hydrogen in O, the element O was assigned, however, it should be H.

**Comment by sobolevnrm** [comment] 2021-06-02 02:04
Hello -- this definitely looks like a bug.  Thank you for letting us know!

**Comment by stefdoerr** [comment] 2021-06-09 12:41
Hi, this is caused by the create_atom function not setting the element and copying the element of the reference atom of the water which is an oxygen. It's fixed in this PR https://github.com/Electrostatics/pdb2pqr/pull/195

**Comment by sobolevnrm** [comment] 2021-12-31 03:18
@stefdoerr claims this has been fixed and I can't reproduce the original error so I am closing the issue.

**Closed by sobolevnrm** 2021-12-31 03:18 UTC
